sudo: required
services:
  - docker

before_install:
  - docker build -t jhesuandhi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jhesuandhi/react-test npm test npm run test -- --watchAll=false

after_success:
  - docker build -t jhesuandhi/docker-multi-client ./client
  - docker build -t jhesuandhi/docker-multi-nginx ./nginx
  - docker build -t jhesuandhi/docker-multi-server ./server
  - docker build -t jhesuandhi/docker-multi-worker ./worker

  # Log in to the docker CLI  (using travis variables)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take these images and push them to docker hub
  - docker push jhesuandhi/docker-multi-client
  - docker push jhesuandhi/docker-multi-nginx
  - docker push jhesuandhi/docker-multi-server
  - docker push jhesuandhi/docker-multi-worker

  # deploy to EBS AWS
  deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: S3 bucker name
    bucket_path: docker-multi
    on:
      branch: master
      access_key_id: $AWS_ACCESS_KEY # configured in travis.org
      secret_access_key:
        secure: $AWS_SECRET_KEY
