sudo: required
services:
  - docker

before_install:
  - docker build -t jhesuandhi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jhesuandhi/react-test npm test npm run test -- --watchAll=false

after_success:
  - docker build -t jhesuandhi/muti-client ./client
  - docker build -t jhesuandhi/multi-nginx ./nginx
  - docker build -t jhesuandhi/multi-server ./server
  - docker build -t jhesuandhi/multi-worker ./worker
  # Log in to the docker CLI  (using travis variables)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # Take these images and push them to docker hub
  - docker push jhesuandhi/muti-client
  - docker push jhesuandhi/multi-nginx
  - docker push jhesuandhi/multi-server
  - docker push jhesuandhi/multi-worker

